months = set(["January", "February", "March", "April", "May", "June"])
print("\nprinting the original set ... ")
print(months)
print("\nRemoving some months from the set...")
months.remove("January")
print("\nPrinting the modified set...")
print(months)
print("\nlooping through the set elements ... ")
for i in months:
    print(i)
