course = 'Python for Beginners'
print(course[0])
print(course[0:4])
print(course[:6])
print(course[0:])
print(course[:])
print(course[-1])
print(course[:-4])
print(len(course))
print(course.upper())
print(course.lower())
print(course.find("h"))
print(course.replace("for", "only for"))
print(course.split())
print(course.index("r"))
print(course.count('n'))
print('Python' in course)
